### ISSUE TITLE
Windows-specific implementations in Folder Sort

### ISSUE THREAD

**Issue by nikramakrishnan** [nikramakrishnan/system-cleaner#3]
Folder sort has a few windows specific implementations that prevent it from working on Mac, Linux and other operating systems. Essentially Folder Sort has become Windows-only after these implementations were added.

I suspect it is ```winpath``` that is causing trouble here.

@ccpandhare could you hop in? Need a mac here :)

**Comment by nikramakrishnan** [comment]
@ccpandhare try cloning [this](../tree/bug/non-windows) branch and see if it works?

**Comment by ccpandhare** [comment]
Yeah sure!

**Comment by ccpandhare** [comment]
Works like a charm!

**Comment by nikramakrishnan** [comment]
Gotcha. Testing in Linux environment now.

**Comment by nikramakrishnan** [comment]
Fixed. Merging and closing.
